### ISSUE TITLE
Year axis range

### ISSUE THREAD

**Issue by ktbacher** [uwdata/lyra#489] opened 2020-09-29 15:48 UTC
- I am reporting a bug

**Expected Behavior**
When year is bound to an axis, it should only span relevant years.

**Actual Behavior**
The order in which data are bound to the axes can affect the final visualization, so when year is bound first, the axis starts at 0.

**Steps to reproduce behavior**
- use car dataset
- select line (or area) mark
- bind year to x axis
- bind mean horsepower to y axis
--> results in an x axis starting from 0
vs.
- car dataset
- select line (or area) mark
- bind mean horsepower to y axis
- bind year to x asix
--> results in an x axis just spanning relevant years

**Comment by jonathanzong** [comment] 2020-11-14 08:24
duplicate of #505

**Closed as completed by jonathanzong** 2020-11-14 08:24 UTC
Labels: bug, lyra2019
